name: Build-Release
on:
  push:
    tags:
      - 'v*'

jobs:
  Build-Docker-Images-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract long version from pyproject.toml
        run: echo "IMAGE_VERSION_LONG=$(grep -m1 '^version' pyproject.toml | awk -F' = |\"' '{print $3}')" >> $GITHUB_ENV

      - name: Extract short version from pyproject.toml
        run: echo "IMAGE_VERSION_SHORT=$(echo ${{ env.IMAGE_VERSION_LONG }} | awk -F'.' '{print $1, $2}' OFS='.')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cap-dcwiz/karez:${{ env.IMAGE_VERSION_LONG }}
            ghcr.io/cap-dcwiz/karez:${{ env.IMAGE_VERSION_SHORT }}
            ghcr.io/cap-dcwiz/karez:latest