name: Clean-Package
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  Clean-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with:
          package-name: 'karez'
          package-type: 'container'
          token: ${{ secrets.GITHUB_TOKEN }}
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'