name: Security Scanning

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
  schedule:
    - cron: '42 13 * * 4'

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depcheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: snok/install-poetry@v1
      - run: poetry export -f requirements.txt --output requirements.txt --without-hashes --without-urls
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: ${{ github.event.repository.name }}
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired
            --enableExperimental
      - name: Upload Test results
        if: success() || failure()
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  sonarqube:
    name: sonarqube-scanning
    runs-on: ubuntu-latest
    if: success() || failure()
    needs: depchecktest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@master
        with:
           name: Depcheck report
           path: ${{ github.workspace }}/reports
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  trivy:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Trivy Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: "Check file existence"
        id: check_dockerfile
        uses: andstor/file-existence-action@v1
        with:
          files: "Dockerfile"
      - id: repo_name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.event.repository.name }}
      - name: Build an image from Dockerfile
        if: steps.check_dockerfile.outputs.files_exists == 'true'
        run: |
          docker build -t ${{ steps.repo_name.outputs.lowercase }}:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner (Sarif)
        if: steps.check_dockerfile.outputs.files_exists == 'true' && !github.event.repository.private
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          image-ref: '${{ steps.repo_name.outputs.lowercase }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
      - name: Upload Trivy scan results to GitHub Security tab
        if: steps.check_dockerfile.outputs.files_exists == 'true' && !github.event.repository.private
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      - name: Run Trivy vulnerability scanner (Html)
        if: steps.check_dockerfile.outputs.files_exists == 'true' && (success() || failure())
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          image-ref: '${{ steps.repo_name.outputs.lowercase }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-results.html'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: 1
      - name: Upload Test results
        if: steps.check_dockerfile.outputs.files_exists == 'true' && (success() || failure())
        uses: actions/upload-artifact@master
        with:
           name: Trivy report
           path: trivy-results.html
      - name: Run Trivy vulnerability scanner (Html Full)
        if: steps.check_dockerfile.outputs.files_exists == 'true' && (success() || failure())
        uses: aquasecurity/trivy-action@2a2157eb22c08c9a1fac99263430307b8d1bc7a2
        with:
          image-ref: '${{ steps.repo_name.outputs.lowercase }}:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-results-full.html'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: false
      - name: Upload Test results
        if: steps.check_dockerfile.outputs.files_exists == 'true' && (success() || failure())        
        uses: actions/upload-artifact@master
        with:
           name: Trivy report
           path: trivy-results-full.html