dispatchers:
  - type: default
    connector: eaton_conn_test
    batch_size: 10
    interval: 10
    entity_file: config/eaton_devices.json

connectors:
  - name: eaton_conn_test
    type: eaton_telemetry
    base_url: http://eatondcimdemo.com/rest
    connection_args:
      timeout: 600
    security:
      type: basic
      username:
      password:
    converter:
      - eaton_telemetry
      - fix_timestamp
      - fmt_ts_point
      - update_info

converters:
  - type: eaton_telemetry
  - type: fix_timestamp
    tz_infos:
      SGT: Aisa/Singapore
  - type: fmt_ts_point
    measurement: eaton_ma
    field_name: ma_name
  - type: update_info
    info_file: config/eaton_device_types.json
    key: dev_id
