dispatchers:
  - type: default
    connector: eaton_conn_test
    batch_size: 10
    interval: 10
    entity_file: config/eaton_devices.json

connectors:
  - name: eaton_conn_test
    type: eaton_telemetry
    base_url: http://eatondcimdemo.com/rest
    connection_args:
      timeout: 600
    security:
      type: basic
      username:
      password:
    converter:
      - eaton_telemetry

converters:
  - type: eaton_telemetry
    next:
      - fix_timestamp
  - type: fix_timestamp
    tz_infos:
      SGT: Aisa/Singapore
    next:
      - influx_json_format
  - type: influx_json_format
    measurement: eaton_ma
    field_name: ma_name
    next:
      - update_info
  - type: update_info
    info_file: config/eaton_device_types.json
    key: dev_id
