dispatchers:
  - type: default
    connector: opcua_conn
    batch_size: 100
    interval: 5
    entity_file: config/opcua_points.json

connectors:
  - name: opcua_conn
    type: opcua
    url: opc.tcp://opcuaserver.com:48010
    converter:
      - update_info
      - fix_timestamp
      - fmt_ts_point

converters:
  - type: fix_timestamp
    tz_infos:
      SGT: Aisa/Singapore
  - type: fmt_ts_point
    measurement: opcua_ma
    field_name: ma_name
    field_value: value
  - type: update_info
    info_file: config/opcua_points_info.json
    key: ma_id

aggregators:
  - type: echo
    categodiry: telemetry