dispatchers:
  - type: default
    connector: opcua_conn
    batch_size: 100
    interval: 5
    entity_file: config/opcua_points.json

connectors:
  - name: opcua_conn
    type: opcua
    url: opc.tcp://opcuaserver.com:48010
    converter:
      - update_info

converters:
  - type: update_info
    info_file: config/opcua_points_info.json
    key: ma_id
    next:
#      - fix_timestamp
      - filter_and_update_meta
#  - type: fix_timestamp
#    tz_infos:
#      SGT: Aisa/Singapore
#    next: influx_json_format
#  - type: influx_json_format
#    measurement: opcua_ma
#    field_name: ma_name
#    field_value: value
  - type: filter_and_update_meta
    key: category
    rename:
      telemetry: telemetry2

aggregators:
  - type: echo
    category: telemetry