dispatchers:
  - type: default
    connector: virtgen_conn
    batch_size: 100
    interval: 120
    entity_file: config/virtgen_devices.json

connectors:
  - name: virtgen_conn
    type: virtgen_telemetry
    base_url: https://dcwiz-platform.staging.rda.ai/api/dc-gateway/virtual-generator
    generator_name: snapshot_ma
    connection_args:
      timeout: 600
      verify: false
    security:
      type: basic
      username:
      password:
    converter:
      - fix_timestamp
      - set_measurement
      - update_info

converters:
  - type: fix_timestamp
    tz_infos:
      SGT: Aisa/Singapore
  - type: set_measurement
    measurement: virtgen_ma
  - type: update_info
    info_file: config/virtgen_device_types.json
    key: dev_id
